# Generated by Django 2.1 on 2018-08-12 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180811_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('conferencia', 'CONFERENCIA'), ('seminario', 'SEMINARIO'), ('congreso', 'CONGRESO'), ('curso', 'CURSO')], default='conferencia', max_length=20)),
                ('place', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('type_event', models.CharField(choices=[('presencial', 'PRESENCIAL'), ('virtual', 'VIRTUAL')], default='presencial', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
